<Test@MDScreen>:
    id: test_screen
    name: "Test"

    MDBoxLayout:
        orientation: "vertical"

        MDBoxLayout:
            orientation: "vertical"

            MDLabel:
                text: "Test"
                halign: "center"
                font_style: "H4"
                size_hint_y: None

            MDProgressBar:
                id: progress_bar
                running_duration: 5
                catching_duration: 10.5
                type: "determinate"

            MDRaisedButton:
                pos_hint: {"center_x": .5, "center_y": .4}
                text: "Start test"
#                                    on_release: app.state = "stop" if app.state == "start" else "start"
                on_release: app.start_test()