MDScreen
    StackLayout:
        orientation: 'lr-tb'

        MDDropDownItem:
            id: difficulty_button
            pos_hint: {'center_x': .5, 'center_y': .5}
            text: 'Difficulty'
            on_release: app.difficulty_menu.open()
            size_hint: 1/3, 0.1

        MDDropDownItem:
            id: operator_button
            pos_hint: {'center_x': .5, 'center_y': .5}
            text: 'Operator'
            on_release: app.operator_menu.open()
            size_hint: 1/3, 0.1

        MDDropDownItem:
            id: duration_button
            pos_hint: {'center_x': .5, 'center_y': .5}
            text: 'Duration'
            on_release: app.duration_menu.open()
            size_hint: 1/3, 0.1