<MyAppTopAppBar@MDTopAppBar>:
#   This is a reusable structure
    title: "Test"
#    elevation: 10
    pos_hint: {"top": 1}
    left_action_items: [["menu", lambda x: app.open_menu()]]
    right_action_items: [["logout", lambda x: app.exit_app()]]

MDScreen:
    id: leaderboard_screen
    name: "Leaderboard"

    MDBoxLayout:
        padding: [10, 10, 10, 10]
        size_hint_y: 0.99
#        spacing: 25
        orientation: "vertical"

        MDLabel:
            text: 'Leaderboard'
            halign: "center"
            font_style: "H4"
            size_hint_y: None

        MDGridLayout:
            cols: 4
            spacing: 10

            MDCard:
                MDGridLayout:
                    rows: 2
#                    MDLabel:
#                        text: 'Addition'
#                        font_style: 'H6'
#                        halign: 'center'
                    MDDataTable:
                        column_data: "Name", "Score"
                        row_data: "Nick", "12"
                        size_hint_x: 0.9
                        size_hint_y: 0.6
                    MDLabel:
                        text: 'Table'
                        halign: 'center'

            MDCard:
                MDGridLayout:
                    rows: 2
                    MDLabel:
                        text: 'Subtraction'
                        font_style: 'H6'
                        halign: 'center'
                    MDLabel:
                        text: 'Table'
                        halign: 'center'

            MDCard:
                MDGridLayout:
                    rows: 2
                    MDLabel:
                        text: 'Multiplication'
                        font_style: 'H6'
                        halign: 'center'
                    MDLabel:
                        text: 'Table'
                        halign: 'center'

            MDCard:
                MDGridLayout:
                    rows: 2
                    MDLabel:
                        text: 'Division'
                        font_style: 'H6'
                        halign: 'center'
                    MDLabel:
                        text: 'Table'
                        halign: 'center'