<MyAppTopAppBar@MDTopAppBar>:
#   This is a reusable structure
    title: "Test"
#    elevation: 10
    pos_hint: {"top": 1}
    left_action_items: [["menu", lambda x: app.open_menu()]]
    right_action_items: [["logout", lambda x: app.exit_app()]]

MDScreen:

    id: test_screen
    name: "Quiz"

    MyAppTopAppBar

    MDGridLayout:
        size_hint_y: 0.8925
        rows: 2
#        size_hint_y: None
#        height: self.minimum_height
        MDProgressBar:
            text: 'Progress bar'
            size_hint_y: .05
            size_hint_x: .65
            value: 50
        MDGridLayout:
            height: self.minimum_height
            cols: 3

            MDProgressBar:
                value: 100
                color: 255, 0, 0, 1
                orientation: 'vertical'
                size_hint_y: .1
                size_hint_x: .1

            MDFloatLayout:

                MDLabel:
                    id: question_label
                    pos_hint: {"center_x": .5, "center_y": .65}
                    halign: 'center'
                    text: "Click button to start"
                    font_style: "H4"
                    theme_text_color: "Custom"
                    text_color: "blue"

                MDTextField:
                    id: answer_input
                    hint_text: "Enter answer"
                    mode: "rectangle"
                    pos_hint: {"center_x": .5, "center_y": .5}
                    size_hint_x: None
                    width: 200
                    multiline: False
                    on_text_validate: app.get_next_question()
                    halign: "center"
                    disabled: True
                    focus: True

                MDRaisedButton:
                    id: next_button
                    pos_hint: {"center_x": .5, "center_y": .3}
                    font_style: "H5"
                    text: "Next question"
                    on_release: app.get_next_question()

            MDProgressBar:
                color: 9, 141, 0, 1
                value: 25
                orientation: 'vertical'
                size_hint_y: .1
                size_hint_x: .1





#    MDFloatLayout:
#
#        MDProgressBar:
#            size_hint_x: .65
#            value: 0
#            pos_hint: {"center_x": .5, "center_y": .8}
##            catching_duration: 10.5
#            type: "determinate"
#            orientation: 'vertical'
#
##        MDProgressBar:
##            size_hint_x: .65
##            value: 0
##            pos_hint: {"center_x": .5, "center_y": .7}
###            catching_duration: 10.5
##            type: "determinate"
#
#
#        MDLabel:
#            id: question_label
#            pos_hint: {"center_x": .5, "center_y": .65}
#            halign: 'center'
#            text: "Click button to start"
#            font_style: "H4"
#            theme_text_color: "Custom"
#            text_color: "blue"
#
#        MDTextField:
#            id: answer_input
#            hint_text: "Enter answer"
#            mode: "rectangle"
#            pos_hint: {"center_x": .5, "center_y": .5}
#            size_hint_x: None
#            width: 200
#            multiline: False
#            on_text_validate: app.get_next_question()
#            halign: "center"
#            disabled: True
#            focus: True
#
#        MDRaisedButton:
#            id: next_button
#            pos_hint: {"center_x": .5, "center_y": .3}
#            font_style: "H5"
#            text: "Next question"
#            on_release: app.get_next_question()